/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AlmoreRouteImport } from './routes/almore'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AlmoreMembrosCompanyIdRouteImport } from './routes/almore-membros.$companyId'
import { Route as AppSupervisaoRouteImport } from './routes/_app.supervisao'
import { Route as AppPendentesRouteImport } from './routes/_app.pendentes'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContatosRouteImport } from './routes/_app.contatos'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'

const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmoreRoute = AlmoreRouteImport.update({
  id: '/almore',
  path: '/almore',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AlmoreMembrosCompanyIdRoute = AlmoreMembrosCompanyIdRouteImport.update({
  id: '/almore-membros/$companyId',
  path: '/almore-membros/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSupervisaoRoute = AppSupervisaoRouteImport.update({
  id: '/supervisao',
  path: '/supervisao',
  getParentRoute: () => AppRoute,
} as any)
const AppPendentesRoute = AppPendentesRouteImport.update({
  id: '/pendentes',
  path: '/pendentes',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContatosRoute = AppContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/almore': typeof AlmoreRoute
  '/login': typeof LoginRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contatos': typeof AppContatosRoute
  '/dashboard': typeof AppDashboardRoute
  '/inbox': typeof AppInboxRoute
  '/pendentes': typeof AppPendentesRoute
  '/supervisao': typeof AppSupervisaoRoute
  '/almore-membros/$companyId': typeof AlmoreMembrosCompanyIdRoute
}
export interface FileRoutesByTo {
  '/almore': typeof AlmoreRoute
  '/login': typeof LoginRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contatos': typeof AppContatosRoute
  '/dashboard': typeof AppDashboardRoute
  '/inbox': typeof AppInboxRoute
  '/pendentes': typeof AppPendentesRoute
  '/supervisao': typeof AppSupervisaoRoute
  '/almore-membros/$companyId': typeof AlmoreMembrosCompanyIdRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/almore': typeof AlmoreRoute
  '/login': typeof LoginRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/contatos': typeof AppContatosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/pendentes': typeof AppPendentesRoute
  '/_app/supervisao': typeof AppSupervisaoRoute
  '/almore-membros/$companyId': typeof AlmoreMembrosCompanyIdRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/almore'
    | '/login'
    | '/trocar-senha'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/inbox'
    | '/pendentes'
    | '/supervisao'
    | '/almore-membros/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/almore'
    | '/login'
    | '/trocar-senha'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/inbox'
    | '/pendentes'
    | '/supervisao'
    | '/almore-membros/$companyId'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/almore'
    | '/login'
    | '/trocar-senha'
    | '/_app/configuracoes'
    | '/_app/contatos'
    | '/_app/dashboard'
    | '/_app/inbox'
    | '/_app/pendentes'
    | '/_app/supervisao'
    | '/almore-membros/$companyId'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AlmoreRoute: typeof AlmoreRoute
  LoginRoute: typeof LoginRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  AlmoreMembrosCompanyIdRoute: typeof AlmoreMembrosCompanyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almore': {
      id: '/almore'
      path: '/almore'
      fullPath: '/almore'
      preLoaderRoute: typeof AlmoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/almore-membros/$companyId': {
      id: '/almore-membros/$companyId'
      path: '/almore-membros/$companyId'
      fullPath: '/almore-membros/$companyId'
      preLoaderRoute: typeof AlmoreMembrosCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/supervisao': {
      id: '/_app/supervisao'
      path: '/supervisao'
      fullPath: '/supervisao'
      preLoaderRoute: typeof AppSupervisaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pendentes': {
      id: '/_app/pendentes'
      path: '/pendentes'
      fullPath: '/pendentes'
      preLoaderRoute: typeof AppPendentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contatos': {
      id: '/_app/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AppContatosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContatosRoute: typeof AppContatosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInboxRoute: typeof AppInboxRoute
  AppPendentesRoute: typeof AppPendentesRoute
  AppSupervisaoRoute: typeof AppSupervisaoRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContatosRoute: AppContatosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInboxRoute: AppInboxRoute,
  AppPendentesRoute: AppPendentesRoute,
  AppSupervisaoRoute: AppSupervisaoRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AlmoreRoute: AlmoreRoute,
  LoginRoute: LoginRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  AlmoreMembrosCompanyIdRoute: AlmoreMembrosCompanyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
